server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  boot:
    admin:
      client:
        url: "http://localhost:9004"
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: EurekaServer
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
